# workflow/profiles/hcc/config.yaml
executor: slurm
jobs: 16

default-resources:
  - mem_mb=8000
  - runtime=60
  - partition=guest,batch
  - account=richlab
  - extra=""
  
use-conda: true
conda-prefix: "/mnt/nrdstor/richlab/aliciarich/conda"

use-apptainer: true
apptainer-args: "--bind /work,/lustre,/mnt/nrdstor,/home"

use-singularity: true
singularity-args: "--bind /work,/lustre,/mnt/nrdstor,/home"
singularity-prefix: "/mnt/nrdstor/richlab/aliciarich/singularity"

latency-wait: 60
restart-times: 1
max-jobs-per-second: 2
printshellcmds: true
verbose: true   

slurm:
  account: "{resources.account}"
  partition: "{resources.partition}"
  time: "{resources.runtime}"
  mem: "{resources.mem_mb}"
  cpus-per-task: "{threads}"
  extra-args: "--account={resources.account} {resources.extra}"
  